### ISSUE TITLE
Destroying 'Session variables' when logout

### ISSUE THREAD

**Issue by ashanaka** [ucsc-2nd-year-group-22/mvc-framework#7]
Regarding controllers/dashboard.php -> logout()
@DDhanushka Why do we delete all the session variables when logout? Won't we need any other session variables after logging out?
`function logout() {
        Session::destroy();
        header('location: ../login');
        exit;
    }`

**Comment by DDhanushka** [comment]
Got your point. I will make a method for unset($key). Then no need to destroy the session. Thanks pren
